language: python
dist: xenial

matrix:
  include:
    - python: 3.7
      env: TOX_ENV=py37-redislite
    - python: 3.7
      env: TOX_ENV=build_docs
    # todo: use a less finnicky linter which has a chance of passing
#    - python: 3.7
#      env: TOX_ENV=pylint
    - python: 3.7
      env: TOX_ENV=pep8
    - python: 3.6
      env: TOX_ENV=py36-redislite
    - python: 3.5
      env: TOX_ENV=py35-redislite
    - python: 2.7
      env: TOX_ENV=py27-redislite
    # todo: test against redis?
  fast_finish: true

before_install:
  - sudo apt-get update -qq
  - pip install tox
script: tox -v -e $TOX_ENV
after_success: coveralls
after_failure:
  - for X in .tox/$TOX_ENV/log/*; do echo "$X\n"; cat "$X"; echo "\n\n"; done
  - echo "pip.log\n"; cat $HOME/.pip/pip.log
